@startuml
folder "Glückwunschkarte" {
    usecase goodbye [
        Lieber Tom,
        wir wünschen dir viel Erfolg und
        alles Gute für die Zukunft!
    ]

    :Daniel: -- goodbye
    :Rene: -- goodbye
    :Frank: -- goodbye
    :Janina: -- goodbye

}
@enduml
