@startuml
folder "Glückwunschkarte" {
    usecase goodbye [
        Lieber Tom,
        wir wünschen dir viel Erfolg und
        alles Gute für die Zukunft!
    ]

    :Daniel: --> goodbye: says
    :Rene: --> goodbye: says
    :Frank: --> goodbye: says
    :Janina: --> goodbye: says
    :NN: --> goodbye: says
}
@enduml
