@startuml
folder "Glückwunschkarte" {
    usecase goodbye [
        Lieber Tom,
        wir wünschen dir viel Erfolg und
        alles Gute für die Zukunft!
    ]

    :Daniel: --> goodbye: says
    :Rene: --> goodbye: says
    :Frank: --> goodbye: says
    :Janina: --> goodbye: says
    :Hartwig: --> goodbye: says
    :Claus-Peter: --> goodbye: says
    :Felix: --> goodbye: says
    :Christian: --> goodbye: says
    :Stefan: --> goodbye: says
    :Klaus: --> goodbye: says
    :Detlef: --> goodbye: says
    :Karsten: --> goodbye: says
    :Shyam: --> goodbye: says
    :MicNet: --> goodbye: says
    :Gordon: --> goodbye: says
    :Frank: --> goodbye: says
    :Arnold: --> goodbye: says 
    :Jens: --> goodbye: says
    :Mario: --> goodbye: says
   
    
}
@enduml
